package com.fitnesstracker.traininginsights.domain;

import static com.fitnesstracker.traininginsights.domain.AnalysisRules.CONSISTENCY_TREND_WEEKS;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.CONSISTENCY_WINDOW_DAYS;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.LOAD_ROUNDING_KG;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.MAX_LOAD_INCREASE_KG;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.MEDICAL_REFERRAL_MESSAGE;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.MIN_LOAD_INCREASE_KG;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.MIN_MEANINGFUL_CHANGE_PCT;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.MIN_SESSIONS_FOR_TREND;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.PLATEAU_MIN_SESSIONS;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.PLATEAU_MIN_SPAN_DAYS;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.PROGRESSION_STEP_PCT;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.TREND_WINDOW_SESSIONS;
import static com.fitnesstracker.traininginsights.domain.AnalysisRules.WEIGHT_COMPARISON_EPSILON_KG;

import com.fitnesstracker.traininginsights.dto.ConsistencyMetrics;
import com.fitnesstracker.traininginsights.dto.DateRange;
import com.fitnesstracker.traininginsights.dto.ExerciseInsight;
import com.fitnesstracker.traininginsights.dto.ExerciseRef;
import com.fitnesstracker.traininginsights.dto.NextSessionSuggestion;
import com.fitnesstracker.traininginsights.dto.PersonalBests;
import com.fitnesstracker.traininginsights.dto.SessionMetrics;
import com.fitnesstracker.traininginsights.dto.VolumeTrend;
import com.fitnesstracker.workouts.entity.ExerciseCategory;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

/**
 * The deterministic analytics engine — a line-for-line port of
 * {@code app/modules/training_insights/analytics.py}.
 *
 * <p>Every method here is pure: no database, no network, no clock. {@code today} is always
 * passed in, so every result is reproducible and unit-testable without fixtures.
 *
 * <p><b>The LLM has no part in any of this.</b> Classifications, metrics, personal bests
 * and consistency counts are computed here and only here; the AI layer receives the
 * finished result and rewords it.
 *
 * <p>Numeric behaviour is pinned to CPython's by {@link PythonNumbers} and verified
 * against fixtures generated by the Python implementation
 * ({@code contract/training-insights-fixtures.json}) — the fixtures are authoritative, not
 * the assumption that the two round alike.
 */
public final class TrainingAnalytics {

    private TrainingAnalytics() {}

    // --- small numeric helpers -----------------------------------------------

    /**
     * A weight of exactly 0 is valid input the API accepts ({@code >= 0}) but carries no
     * load information, so it is treated as unweighted.
     */
    private static boolean isWeighted(Double weightKg) {
        return weightKg != null && weightKg > WEIGHT_COMPARISON_EPSILON_KG;
    }

    private static boolean sameWeight(double left, double right) {
        return Math.abs(left - right) < WEIGHT_COMPARISON_EPSILON_KG;
    }

    /**
     * Percentage change, or null when it cannot be expressed.
     *
     * <p>A zero baseline has no meaningful percentage change, so this returns null rather
     * than infinity — callers read null as "no signal", never as "no change".
     */
    public static Double percentChange(Double baseline, Double latest) {
        if (baseline == null || latest == null) {
            return null;
        }
        if (Math.abs(baseline) < WEIGHT_COMPARISON_EPSILON_KG) {
            return null;
        }
        return PythonNumbers.round((latest - baseline) / baseline * 100.0, 1);
    }

    private static boolean isMeaningful(Double changePercent) {
        return changePercent != null && Math.abs(changePercent) >= MIN_MEANINGFUL_CHANGE_PCT;
    }

    /** Peak-to-trough spread of a series as a percentage of its smallest value. */
    private static Double spreadPercent(List<Double> values) {
        if (values.isEmpty()) {
            return null;
        }
        double low = values.stream().mapToDouble(Double::doubleValue).min().orElseThrow();
        double high = values.stream().mapToDouble(Double::doubleValue).max().orElseThrow();
        if (Math.abs(low) < WEIGHT_COMPARISON_EPSILON_KG) {
            return null;
        }
        return PythonNumbers.round((high - low) / low * 100.0, 1);
    }

    // --- session aggregation -------------------------------------------------

    /**
     * Collapses raw rows into one {@link SessionMetrics} per workout, oldest first.
     *
     * <p>Handles the awkward realities of logged data: rows arriving in any order, several
     * workouts sharing a date, and the same exercise appearing more than once inside one
     * workout. Ordering is {@code (performedAt, workoutCreatedAt, workoutId)} so the result
     * is stable even when two workouts share a date.
     */
    public static List<SessionMetrics> buildSessions(List<LoggedSet> entries) {
        Map<UUID, List<LoggedSet>> grouped = new LinkedHashMap<>();
        for (LoggedSet entry : entries) {
            grouped.computeIfAbsent(entry.workoutId(), key -> new ArrayList<>()).add(entry);
        }

        List<SessionMetrics> sessions = new ArrayList<>();
        Map<UUID, LoggedSet> firstRowByWorkout = new LinkedHashMap<>();

        for (List<LoggedSet> rows : grouped.values()) {
            LoggedSet first = rows.get(0);
            firstRowByWorkout.put(first.workoutId(), first);

            int totalSets = rows.stream().mapToInt(LoggedSet::sets).sum();
            int totalReps = rows.stream().mapToInt(row -> row.sets() * row.reps()).sum();

            Integer repsPerSet = rows.stream().map(LoggedSet::reps).distinct().count() == 1
                    ? first.reps()
                    : null;

            List<LoggedSet> weighted = rows.stream().filter(row -> isWeighted(row.weightKg()))
                    .toList();
            Double topWeight = weighted.stream()
                    .map(LoggedSet::weightKg)
                    .max(Comparator.naturalOrder())
                    .orElse(null);
            Double volume = weighted.isEmpty() ? null : PythonNumbers.round(
                    weighted.stream()
                            .mapToDouble(row -> row.sets() * row.reps() * row.weightKg())
                            .sum(),
                    2);

            sessions.add(new SessionMetrics(
                    first.workoutId(), first.performedAt(), totalSets, totalReps,
                    repsPerSet, topWeight, volume));
        }

        sessions.sort(Comparator
                .comparing(SessionMetrics::performedAt)
                .thenComparing(session -> firstRowByWorkout.get(session.workoutId())
                        .workoutCreatedAt())
                .thenComparing(session -> session.workoutId().toString()));
        return sessions;
    }

    public static boolean sessionHasMedicalNote(List<LoggedSet> entries) {
        return entries.stream().anyMatch(LoggedSet::hasMedicalNote);
    }

    // --- personal bests ------------------------------------------------------

    /**
     * Records over whatever history was queried.
     *
     * <p>Returns empty fields rather than inventing a record when no session carried a
     * weight. Ties go to the earliest date: a record is dated from when it was first set.
     */
    public static PersonalBests findPersonalBests(List<SessionMetrics> sessions) {
        List<SessionMetrics> weighted = sessions.stream()
                .filter(session -> session.topWeightKg() != null).toList();
        if (weighted.isEmpty()) {
            return PersonalBests.empty();
        }

        SessionMetrics heaviest = earliestBest(weighted, SessionMetrics::topWeightKg);
        double heaviestWeight = heaviest.topWeightKg();

        List<SessionMetrics> withVolume = sessions.stream()
                .filter(session -> session.volumeKg() != null).toList();
        SessionMetrics bestVolume = withVolume.isEmpty()
                ? null
                : earliestBest(withVolume, SessionMetrics::volumeKg);

        // "Most reps at your heaviest load" compares only sessions at that load, so a
        // light high-rep day can never masquerade as a record here.
        List<SessionMetrics> atHeaviest = weighted.stream()
                .filter(session -> sameWeight(session.topWeightKg(), heaviestWeight)).toList();
        SessionMetrics mostReps = earliestBest(
                atHeaviest, session -> (double) session.totalReps());

        return new PersonalBests(
                heaviestWeight,
                heaviest.performedAt(),
                bestVolume == null ? null : bestVolume.volumeKg(),
                bestVolume == null ? null : bestVolume.performedAt(),
                mostReps.totalReps(),
                mostReps.performedAt());
    }

    private static SessionMetrics earliestBest(
            List<SessionMetrics> candidates,
            java.util.function.Function<SessionMetrics, Double> value) {
        return candidates.stream()
                .max(Comparator
                        .comparingDouble((SessionMetrics session) -> value.apply(session))
                        .thenComparing(SessionMetrics::performedAt, Comparator.reverseOrder()))
                .orElseThrow();
    }

    // --- trend classification ------------------------------------------------

    /** The sessions a verdict is computed from, plus which metric drives it. */
    public record Window(List<SessionMetrics> sessions, MetricBasis basis) {

        Double primary(SessionMetrics session) {
            if (basis == MetricBasis.LOAD) {
                return session.topWeightKg();
            }
            if (basis == MetricBasis.REPS) {
                return (double) session.totalReps();
            }
            return null;
        }

        List<Double> primarySeries() {
            return sessions.stream().map(this::primary).filter(java.util.Objects::nonNull)
                    .toList();
        }

        List<Double> volumeSeries() {
            if (basis != MetricBasis.LOAD) {
                return List.of();
            }
            return sessions.stream().map(SessionMetrics::volumeKg)
                    .filter(java.util.Objects::nonNull).toList();
        }
    }

    /**
     * Picks the analysis window and the metric that drives classification.
     *
     * <p>Load wins when there is enough weighted history to trust it; otherwise the engine
     * falls back to total reps, which is the only honest signal for a bodyweight strength
     * exercise such as a push-up or pull-up.
     */
    private static Window selectWindow(List<SessionMetrics> sessions) {
        List<SessionMetrics> window = sessions.size() <= TREND_WINDOW_SESSIONS
                ? List.copyOf(sessions)
                : List.copyOf(sessions.subList(sessions.size() - TREND_WINDOW_SESSIONS,
                        sessions.size()));
        List<SessionMetrics> weighted = window.stream()
                .filter(session -> session.topWeightKg() != null).toList();
        if (weighted.size() >= MIN_SESSIONS_FOR_TREND) {
            return new Window(weighted, MetricBasis.LOAD);
        }
        return new Window(window, MetricBasis.REPS);
    }

    /** The verdict, the window it was computed from, and the evidence. */
    public record Verdict(
            TrendClassification classification, Window window, List<String> evidence) {}

    public static Verdict classify(List<SessionMetrics> sessions, ExerciseCategory category) {
        if (category != ExerciseCategory.STRENGTH) {
            return new Verdict(
                    TrendClassification.NOT_APPLICABLE,
                    new Window(List.of(), MetricBasis.NONE),
                    List.of("Trend analysis is defined for strength exercises; logged sets "
                            + "and reps do not describe a comparable workload for "
                            + category.getValue() + " work"));
        }

        Window window = selectWindow(sessions);
        if (window.sessions().size() < MIN_SESSIONS_FOR_TREND) {
            int count = window.sessions().size();
            return new Verdict(
                    TrendClassification.INSUFFICIENT_DATA,
                    window,
                    List.of(count + " comparable session" + (count == 1 ? "" : "s")
                            + " logged; at least " + MIN_SESSIONS_FOR_TREND
                            + " are needed to classify a trend"));
        }

        List<String> plateauEvidence = plateauVerdict(window);
        if (plateauEvidence != null) {
            return new Verdict(TrendClassification.POSSIBLE_PLATEAU, window, plateauEvidence);
        }

        SessionMetrics first = window.sessions().get(0);
        SessionMetrics last = window.sessions().get(window.sessions().size() - 1);
        Double primaryChange = percentChange(window.primary(first), window.primary(last));
        Double volumeChange = percentChange(first.volumeKg(), last.volumeKg());

        String metricLabel = window.basis() == MetricBasis.LOAD ? "Top load" : "Total reps";
        String unit = window.basis() == MetricBasis.LOAD ? " kg" : "";
        Double baselineValue = window.primary(first);
        Double latestValue = window.primary(last);

        String changeLine = (baselineValue != null && latestValue != null && primaryChange != null)
                ? metricLabel + " moved from " + PythonNumbers.formatG(baselineValue) + unit
                        + " to " + PythonNumbers.formatG(latestValue) + unit + " across "
                        + window.sessions().size() + " sessions ("
                        + PythonNumbers.formatSignedOneDecimal(primaryChange) + "%)"
                : metricLabel + " could not be compared across the window";

        String thresholdText = PythonNumbers.formatOneDecimal(MIN_MEANINGFUL_CHANGE_PCT);

        if (isMeaningful(primaryChange) && primaryChange > 0) {
            if (volumeChange != null && volumeChange <= -MIN_MEANINGFUL_CHANGE_PCT) {
                // Heavier but meaningfully less total work: a trade-off, not progress.
                return new Verdict(TrendClassification.STABLE, window, List.of(
                        changeLine,
                        "Session volume fell " + PythonNumbers.formatOneDecimal(volumeChange)
                                + "%, so the increase in load was offset by less total work"));
            }
            List<String> evidence = new ArrayList<>();
            evidence.add(changeLine);
            int streak = consecutiveIncreases(window);
            if (streak >= 2) {
                evidence.add(metricLabel + " increased in " + streak + " consecutive sessions");
            }
            if (volumeChange != null) {
                evidence.add("Session volume changed by "
                        + PythonNumbers.formatSignedOneDecimal(volumeChange) + "%");
            }
            return new Verdict(TrendClassification.PROGRESSING, window, List.copyOf(evidence));
        }

        if (isMeaningful(primaryChange) && primaryChange < 0) {
            List<String> evidence = new ArrayList<>();
            evidence.add(changeLine);
            if (volumeChange != null) {
                evidence.add("Session volume changed by "
                        + PythonNumbers.formatSignedOneDecimal(volumeChange) + "%");
            }
            return new Verdict(TrendClassification.DECLINING, window, List.copyOf(evidence));
        }

        List<String> evidence = new ArrayList<>();
        evidence.add(changeLine);
        if (primaryChange != null) {
            evidence.add("That is under the " + thresholdText + "% threshold for a trend");
        }
        if (volumeChange != null) {
            evidence.add("Session volume changed by "
                    + PythonNumbers.formatSignedOneDecimal(volumeChange) + "%");
        }
        if (window.sessions().size() < PLATEAU_MIN_SESSIONS) {
            evidence.add(PLATEAU_MIN_SESSIONS
                    + " sessions are needed before a plateau can be reported");
        }
        return new Verdict(TrendClassification.STABLE, window, List.copyOf(evidence));
    }

    /** Evidence when the tail of the window is flat for long enough; null otherwise. */
    private static List<String> plateauVerdict(Window window) {
        if (window.sessions().size() < PLATEAU_MIN_SESSIONS) {
            return null;
        }
        List<SessionMetrics> tail = window.sessions()
                .subList(window.sessions().size() - PLATEAU_MIN_SESSIONS, window.sessions().size());

        long spanDays = ChronoUnit.DAYS.between(
                tail.get(0).performedAt(), tail.get(tail.size() - 1).performedAt());
        if (spanDays < PLATEAU_MIN_SPAN_DAYS) {
            // Four hard sessions in one week is a training block, not a plateau.
            return null;
        }

        Window tailWindow = new Window(List.copyOf(tail), window.basis());
        Double primarySpread = spreadPercent(tailWindow.primarySeries());
        if (primarySpread == null || primarySpread >= MIN_MEANINGFUL_CHANGE_PCT) {
            return null;
        }
        Double volumeSpread = spreadPercent(tailWindow.volumeSeries());
        if (volumeSpread != null && volumeSpread >= MIN_MEANINGFUL_CHANGE_PCT) {
            return null;
        }

        String metricLabel = window.basis() == MetricBasis.LOAD ? "load" : "total reps";
        String thresholdText = PythonNumbers.formatOneDecimal(MIN_MEANINGFUL_CHANGE_PCT);

        List<String> evidence = new ArrayList<>();
        evidence.add("No meaningful change in " + metricLabel + " across the last "
                + PLATEAU_MIN_SESSIONS + " comparable sessions");
        evidence.add("Those sessions span " + spanDays + " days (a plateau needs at least "
                + PLATEAU_MIN_SPAN_DAYS + ")");
        evidence.add(capitalize(metricLabel) + " varied by "
                + PythonNumbers.formatOneDecimal(primarySpread) + "%, under the "
                + thresholdText + "% threshold");
        if (volumeSpread != null) {
            evidence.add("Session volume varied by "
                    + PythonNumbers.formatOneDecimal(volumeSpread) + "%, under the "
                    + thresholdText + "% threshold");
        }
        return List.copyOf(evidence);
    }

    /** Python's {@code str.capitalize()}: first character upper, the rest lower. */
    private static String capitalize(String text) {
        if (text.isEmpty()) {
            return text;
        }
        return text.substring(0, 1).toUpperCase(Locale.ROOT)
                + text.substring(1).toLowerCase(Locale.ROOT);
    }

    /** Longest run of strictly increasing steps ending at the latest session. */
    private static int consecutiveIncreases(Window window) {
        List<Double> values = window.primarySeries();
        int streak = 0;
        for (int index = values.size() - 1; index > 0; index--) {
            if (values.get(index) - values.get(index - 1) > WEIGHT_COMPARISON_EPSILON_KG) {
                streak++;
            } else {
                break;
            }
        }
        return streak;
    }

    // --- next-session suggestions --------------------------------------------

    /**
     * A conservative, hard-bounded next load, or null if one cannot be formed.
     *
     * <p>The raw step is {@link AnalysisRules#PROGRESSION_STEP_PCT} of the current load,
     * clamped into [{@link AnalysisRules#MIN_LOAD_INCREASE_KG},
     * {@link AnalysisRules#MAX_LOAD_INCREASE_KG}] and rounded to
     * {@link AnalysisRules#LOAD_ROUNDING_KG} so the number is actually loadable.
     */
    public static Double suggestNextLoadKg(double currentLoadKg) {
        if (currentLoadKg <= WEIGHT_COMPARISON_EPSILON_KG) {
            return null;
        }
        double rawStep = currentLoadKg * PROGRESSION_STEP_PCT / 100.0;
        double clamped = Math.min(Math.max(rawStep, MIN_LOAD_INCREASE_KG), MAX_LOAD_INCREASE_KG);
        // Python: round(clamped / LOAD_ROUNDING_KG) * LOAD_ROUNDING_KG — banker's rounding
        // on the quotient, which Math.round would get wrong on a .5 tie.
        double step = PythonNumbers.roundToLong(clamped / LOAD_ROUNDING_KG) * LOAD_ROUNDING_KG;
        if (step <= 0) {
            return null;
        }
        return PythonNumbers.round(currentLoadKg + step, 2);
    }

    /** Maps a verdict onto a conservative suggestion. Never auto-applied. */
    public static NextSessionSuggestion buildSuggestion(
            TrendClassification classification, Window window, boolean hasMedicalNote) {
        if (hasMedicalNote) {
            return NextSessionSuggestion.of(
                    SuggestionKind.CONSULT_PROFESSIONAL,
                    MEDICAL_REFERRAL_MESSAGE,
                    "A recent note for this exercise mentions pain or injury, which this "
                            + "application is not qualified to act on.");
        }

        if (classification == TrendClassification.INSUFFICIENT_DATA
                || classification == TrendClassification.NOT_APPLICABLE) {
            return NextSessionSuggestion.of(
                    SuggestionKind.INSUFFICIENT_HISTORY,
                    "Not enough comparable history to suggest a change yet.",
                    "A suggestion needs at least " + MIN_SESSIONS_FOR_TREND
                            + " comparable strength sessions for this exercise.");
        }

        if (classification == TrendClassification.PROGRESSING) {
            return NextSessionSuggestion.of(
                    SuggestionKind.MAINTAIN,
                    "Keep doing what you're doing — your current progression is working.",
                    "Recent sessions already show a meaningful upward trend.");
        }

        if (classification == TrendClassification.POSSIBLE_PLATEAU
                || classification == TrendClassification.DECLINING) {
            return NextSessionSuggestion.of(
                    SuggestionKind.REVIEW_EXERCISE,
                    "Worth reviewing this exercise — consider changing the rep range, "
                            + "adjusting how much you do, or swapping in a variation.",
                    "Adding load is not the right response to a flat or falling trend, so "
                            + "no load increase is suggested.");
        }

        // Stable.
        SessionMetrics latest = window.sessions().isEmpty()
                ? null
                : window.sessions().get(window.sessions().size() - 1);
        Double current = latest == null ? null : latest.topWeightKg();
        if (window.basis() == MetricBasis.LOAD && current != null) {
            Double suggested = suggestNextLoadKg(current);
            if (suggested != null) {
                return new NextSessionSuggestion(
                        SuggestionKind.SMALL_PROGRESSION,
                        "If the last session felt manageable, you could try "
                                + PythonNumbers.formatG(suggested) + " kg next time.",
                        "Performance has been steady, so this suggests about "
                                + PythonNumbers.formatOneDecimal(PROGRESSION_STEP_PCT)
                                + "% more load — capped at "
                                + PythonNumbers.formatG(MAX_LOAD_INCREASE_KG)
                                + " kg. It is a suggestion only; nothing changes unless you "
                                + "apply it.",
                        current,
                        suggested);
            }
        }

        return NextSessionSuggestion.of(
                SuggestionKind.MAINTAIN,
                "Maintain your current workload.",
                "Recent sessions have been steady, with no change large enough to act on.");
    }

    // --- assembly ------------------------------------------------------------

    /** Turns raw rows into a full, explained verdict. The single entry point. */
    public static ExerciseInsight buildExerciseInsight(
            ExerciseRef exercise, List<LoggedSet> entries) {
        List<SessionMetrics> sessions = buildSessions(entries);
        Verdict verdict = classify(sessions, exercise.category());
        boolean hasMedicalNote = sessionHasMedicalNote(entries);
        NextSessionSuggestion suggestion =
                buildSuggestion(verdict.classification(), verdict.window(), hasMedicalNote);

        List<SessionMetrics> analyzed = verdict.window().sessions();
        DateRange dateRange = analyzed.isEmpty() ? null : new DateRange(
                analyzed.get(0).performedAt(),
                analyzed.get(analyzed.size() - 1).performedAt());

        List<String> evidence = new ArrayList<>(verdict.evidence());
        if (dateRange != null) {
            evidence.add("Analysis window: " + dateRange.fromDate() + " to " + dateRange.toDate());
        }

        SessionMetrics first = analyzed.isEmpty() ? null : analyzed.get(0);
        SessionMetrics last = analyzed.isEmpty() ? null : analyzed.get(analyzed.size() - 1);
        Double primaryChange = (first != null && last != null)
                ? percentChange(verdict.window().primary(first), verdict.window().primary(last))
                : null;
        Double volumeChange = (first != null && last != null)
                ? percentChange(first.volumeKg(), last.volumeKg())
                : null;

        ExerciseInsight insight = new ExerciseInsight(
                exercise,
                verdict.classification(),
                verdict.window().basis(),
                analyzed.size(),
                dateRange,
                last == null ? null : last.topWeightKg(),
                analyzed.size() >= 2 ? analyzed.get(analyzed.size() - 2).topWeightKg() : null,
                primaryChange,
                volumeChange,
                verdict.classification() == TrendClassification.POSSIBLE_PLATEAU,
                List.copyOf(evidence),
                suggestion,
                "",
                "deterministic");
        return insight.withExplanation(buildFallbackExplanation(insight), "deterministic");
    }

    /**
     * Plain-language prose built from the computed numbers alone.
     *
     * <p>This is what the feature shows when OpenAI is not configured, is down, or was
     * simply not asked — which is why analytics never depend on AI availability.
     */
    public static String buildFallbackExplanation(ExerciseInsight insight) {
        String name = insight.exercise().name();
        int count = insight.sessionsAnalyzed();

        if (insight.classification() == TrendClassification.NOT_APPLICABLE) {
            return name + " is logged as " + insight.exercise().category().getValue()
                    + " work, and sets and reps alone don't describe a comparable workload "
                    + "for it, so no trend is reported.";
        }
        if (insight.classification() == TrendClassification.INSUFFICIENT_DATA) {
            return "There " + (count == 1 ? "is" : "are") + " " + count + " comparable "
                    + name + " session" + (count == 1 ? "" : "s") + " on record. "
                    + MIN_SESSIONS_FOR_TREND + " are needed before a trend can be reported.";
        }

        String detail;
        if (insight.metricBasis() == MetricBasis.LOAD) {
            detail = (insight.previousWeightKg() != null && insight.currentWeightKg() != null)
                    ? "top load went from " + PythonNumbers.formatG(insight.previousWeightKg())
                            + " kg to " + PythonNumbers.formatG(insight.currentWeightKg()) + " kg"
                    : "load stayed in the same range";
        } else {
            detail = "this is based on total reps, since these sessions were logged without "
                    + "a weight";
        }

        return switch (insight.classification()) {
            case PROGRESSING -> "Your " + name + " is progressing: across the last " + count
                    + " sessions, " + detail + ", and total session volume held up.";
            case POSSIBLE_PLATEAU -> "Your " + name + " may have plateaued: the last "
                    + PLATEAU_MIN_SESSIONS + " sessions show no meaningful change in load, "
                    + "reps or volume over at least " + PLATEAU_MIN_SPAN_DAYS + " days.";
            case DECLINING -> "Your " + name + " has trended down across the last " + count
                    + " sessions — " + detail
                    + ". That is often just a normal fluctuation in training.";
            default -> "Your " + name + " has been steady across the last " + count
                    + " sessions, with no change large enough to count as a trend.";
        };
    }

    // --- consistency and workload --------------------------------------------

    /**
     * Factual counts only — how often the user trained, not how recovered they are.
     *
     * <p>Future-dated workouts are ignored: the schema has no planned/completed flag, so a
     * workout dated ahead of today cannot be counted as something that happened.
     */
    public static ConsistencyMetrics computeConsistency(
            List<LocalDate> workoutDates, LocalDate today) {
        List<LocalDate> performed = workoutDates.stream()
                .filter(date -> !date.isAfter(today)).toList();

        LocalDate currentStart = today.minusDays(CONSISTENCY_WINDOW_DAYS - 1L);
        LocalDate previousStart = currentStart.minusDays(CONSISTENCY_WINDOW_DAYS);

        int last7 = (int) performed.stream()
                .filter(date -> !date.isBefore(currentStart) && !date.isAfter(today)).count();
        int previous7 = (int) performed.stream()
                .filter(date -> !date.isBefore(previousStart) && date.isBefore(currentStart))
                .count();

        LocalDate trendStart = today.minusDays(CONSISTENCY_TREND_WEEKS * 7L - 1);
        List<LocalDate> inTrend = performed.stream()
                .filter(date -> !date.isBefore(trendStart) && !date.isAfter(today)).toList();
        int activeWeeks = (int) inTrend.stream()
                .map(date -> ChronoUnit.DAYS.between(trendStart, date) / 7)
                .distinct().count();
        double average = PythonNumbers.round(
                (double) inTrend.size() / CONSISTENCY_TREND_WEEKS, 1);

        return new ConsistencyMetrics(
                last7, previous7, last7 - previous7, activeWeeks, CONSISTENCY_TREND_WEEKS,
                average);
    }

    /**
     * Weighted volume over the current vs previous 7 days.
     *
     * <p>Rows without a weight contribute nothing — there is no defensible way to add a
     * bodyweight plank to a barbell squat.
     */
    public static VolumeTrend computeVolumeTrend(List<LoggedSet> entries, LocalDate today) {
        LocalDate currentStart = today.minusDays(CONSISTENCY_WINDOW_DAYS - 1L);
        LocalDate previousStart = currentStart.minusDays(CONSISTENCY_WINDOW_DAYS);

        double current = 0.0;
        double previous = 0.0;
        for (LoggedSet entry : entries) {
            if (!isWeighted(entry.weightKg())) {
                continue;
            }
            double volume = entry.sets() * entry.reps() * entry.weightKg();
            LocalDate date = entry.performedAt();
            if (!date.isBefore(currentStart) && !date.isAfter(today)) {
                current += volume;
            } else if (!date.isBefore(previousStart) && date.isBefore(currentStart)) {
                previous += volume;
            }
        }

        double roundedCurrent = PythonNumbers.round(current, 2);
        double roundedPrevious = PythonNumbers.round(previous, 2);
        return new VolumeTrend(
                roundedCurrent, roundedPrevious, percentChange(previous, current));
    }
}
