"""Generate JWT compatibility fixtures from the Python backend's own token code.

Run from the repository root:

    backend/.venv/bin/python contract/generate_jwt_fixtures.py

The Java test suite consumes contract/jwt-fixtures.json and asserts that tokens minted by
PyJWT are accepted (or rejected, for the negative cases) exactly as the Python backend
would treat them. Regenerate only when the Python token format deliberately changes.

Nothing here is a secret: the signing key is a fixed test value shared with
TestSecrets.SHARED_JWT_SECRET so both languages sign identically.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
import uuid
from datetime import UTC, datetime, timedelta

SHARED_SECRET = "contract-test-shared-secret-key-0123456789abcdefghijklmnopqrstuv"

os.environ.setdefault("SECRET_KEY", SHARED_SECRET)
os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://unused@/unused")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "backend"))

import jwt  # noqa: E402

ALGORITHM = "HS256"


def encode(payload: dict, secret: str = SHARED_SECRET) -> str:
    return jwt.encode(payload, secret, algorithm=ALGORITHM)


def base_claims(user_id: str, token_type: str, *, issued: datetime, expires: datetime) -> dict:
    return {
        "sub": user_id,
        "type": token_type,
        "jti": str(uuid.uuid4()),
        "iat": issued,
        "exp": expires,
    }


def main() -> None:
    now = datetime.now(UTC)
    user_id = str(uuid.uuid4())
    other_user_id = str(uuid.uuid4())

    # Acceptance fixtures are deliberately long-lived. A fixture minted with the real
    # 15-minute TTL stops being a valid token an hour later, and a compatibility test that
    # fails with the passage of time is worse than no test. The real TTLs are asserted
    # separately against ttl_reference, by inspecting exp - iat rather than by using the
    # token.
    long_life = timedelta(days=3650)
    access_claims = base_claims(
        user_id, "access", issued=now, expires=now + long_life
    ) | {"role": "user", "email_verified": False}
    admin_claims = base_claims(
        other_user_id, "access", issued=now, expires=now + long_life
    ) | {"role": "admin", "email_verified": True}

    document = {
        "_comment": (
            "JWTs produced by the Python backend (PyJWT, app/core/security.py). The Java "
            "backend must treat each exactly as described. Generated by "
            "contract/generate_jwt_fixtures.py."
        ),
        "algorithm": ALGORITHM,
        "secret": SHARED_SECRET,
        "access_token_ttl_seconds": 900,
        "refresh_token_ttl_seconds": 7 * 24 * 3600,
        "claims": {
            "access": ["sub", "role", "email_verified", "type", "jti", "iat", "exp"],
            "refresh": ["sub", "type", "jti", "iat", "exp"],
            "issuer": None,
            "audience": None,
        },
        "accepted_access_tokens": [
            {
                "description": "standard access token for an unverified user",
                "user_id": user_id,
                "role": "user",
                "email_verified": False,
                "token": encode(access_claims),
            },
            {
                "description": "admin access token for a verified user",
                "user_id": other_user_id,
                "role": "admin",
                "email_verified": True,
                "token": encode(admin_claims),
            },
        ],
        "accepted_refresh_tokens": [
            {
                "description": "standard refresh token",
                "user_id": user_id,
                "jti": (refresh := base_claims(
                    user_id, "refresh", issued=now, expires=now + long_life
                ))["jti"],
                "token": encode(refresh),
            }
        ],
        "ttl_reference": {
            "_comment": (
                "Minted with the production TTLs. Used to assert exp - iat, not to "
                "authenticate — these expire like any real token."
            ),
            "access": encode(base_claims(
                user_id, "access", issued=now, expires=now + timedelta(minutes=15)
            ) | {"role": "user", "email_verified": False}),
            "refresh": encode(base_claims(
                user_id, "refresh", issued=now, expires=now + timedelta(days=7)
            )),
        },
        "rejected_tokens": [
            {
                "description": "expired access token",
                "expected_code": "TOKEN_EXPIRED",
                "token": encode(base_claims(
                    user_id, "access",
                    issued=now - timedelta(hours=2),
                    expires=now - timedelta(hours=1),
                ) | {"role": "user", "email_verified": False}),
            },
            {
                "description": "access token signed with the wrong key",
                "expected_code": "UNAUTHORIZED",
                "token": encode(access_claims, secret="a-different-secret-of-sufficient-length-32"),
            },
            {
                "description": "refresh token presented where an access token is required",
                "expected_code": "UNAUTHORIZED",
                "token": encode(base_claims(
                    user_id, "refresh", issued=now, expires=now + long_life
                )),
            },
            {
                # Long-lived like the other negatives: every case except the two named
                # "expired" must fail for the reason under test, not because the fixture
                # aged out between generation and the test run.
                "description": "token with no type claim",
                "expected_code": "UNAUTHORIZED",
                "token": encode({
                    "sub": user_id,
                    "jti": str(uuid.uuid4()),
                    "iat": now,
                    "exp": now + long_life,
                }),
            },
            {
                "description": "token whose sub is not a UUID",
                "expected_code": "UNAUTHORIZED",
                "token": encode(base_claims(
                    "not-a-uuid", "access", issued=now, expires=now + long_life
                ) | {"role": "user", "email_verified": False}),
            },
            {
                "description": "structurally malformed token",
                "expected_code": "UNAUTHORIZED",
                "token": "not.a.jwt",
            },
            {
                "description": "token with a tampered payload segment",
                "expected_code": "UNAUTHORIZED",
                "token": (lambda t: t.split(".")[0] + ".eyJzdWIiOiJ0YW1wZXJlZCJ9." + t.split(".")[2])(
                    encode(access_claims)
                ),
            },
        ],
        "rejected_refresh_tokens": [
            {
                "description": "access token presented where a refresh token is required",
                "expected_code": "UNAUTHORIZED",
                "token": encode(access_claims),
            },
            {
                "description": "expired refresh token",
                "expected_code": "TOKEN_EXPIRED",
                "token": encode(base_claims(
                    user_id, "refresh",
                    issued=now - timedelta(days=30),
                    expires=now - timedelta(days=1),
                )),
            },
        ],
    }

    out = pathlib.Path(__file__).resolve().parent / "jwt-fixtures.json"
    out.write_text(json.dumps(document, indent=2) + "\n")
    print(f"wrote {out}")
    print(f"  accepted access:  {len(document['accepted_access_tokens'])}")
    print(f"  accepted refresh: {len(document['accepted_refresh_tokens'])}")
    print(f"  rejected access:  {len(document['rejected_tokens'])}")
    print(f"  rejected refresh: {len(document['rejected_refresh_tokens'])}")


if __name__ == "__main__":
    main()
